### ISSUE TITLE
TypeError (Can't convert Hash into String) OAuth2 client

### ISSUE THREAD

**Issue by jagwire** [google/signet#41]
While I thought it was to be fixed in c3efb8b68cfdca8a50a6435c401cfd0665500d1b I'm still seeing this issue at oauth_2/client.rb:258

I'm merely following the example from: https://developers.google.com/drive/web/credentials

Please advise.

**Comment by joncalhoun** [comment]
This appears to still exist, at least when using this example: https://developers.google.com/api-client-library/ruby/auth/web-app#example

It looks like the line

```ruby
session[:credentials] = auth_client.to_json
```
results in a redirect_uri that is a hash instead of a string. eg:

```json
{
  ...
  "redirect_uri": {
    "scheme": "http",
    "user": null,
    "password": null,
    "host": "localhost",
    "port": 3000,
    "path": "/oauth/callback",
    "query": null,
    "fragment": null
  },
  ...
}
```

Signet passes this redirect_uri hash directly to `Addressable::URI#parse` which doesn't support converting a hash to a URI. (see https://github.com/google/signet/blob/03bdf5f9ffdc90570fc40caa352a9629d1a904d1/lib/signet/oauth_2/client.rb#L447 and http://www.rubydoc.info/gems/addressable/Addressable/URI#parse-class_method)

I believe this could be fixed by using `Addressable::URI`'s merge method, but you would have to symbolize the keys coming in, so something like:

```ruby
def redirect_uri=(new_redirect_uri)
  new_redirect_uri = build_uri(uri)

  #TODO - Better solution to allow google postmessage flow. For now, make an exception to the spec.
  if new_redirect_uri == nil|| new_redirect_uri.absolute? || uri_is_postmessage?(new_redirect_uri) || uri_is_oob?(new_redirect_uri)
    @redirect_uri = new_redirect_uri
  else
    raise ArgumentError, "Redirect URI must be an absolute URI."
  end
end

def build_uri(uri)
  if uri.is_a?(Hash)
    uri_from_hash(uri)
  else
    Addressable::URI.parse(uri)
  end
end

def uri_from_hash(hash)
  symbolized = {}
  hash.each_key do |k|
    symbolized[(k.to_sym rescue k)] = hash[k]
  end
  Addressable::URI.new.merge(symbolized)
end
```

I'll turn this into a PR with tests and submit it for you to review.

**Comment by joncalhoun** [comment]
Scratch that - this use case was handled in the authorization_uri setter. Using that solution.
