### ISSUE TITLE
Expand faraday version support

### ISSUE THREAD

**Issue by jwg2s** [google/signet#91]
Any reason this is locked to v0.9.x?  Causing all kind of compatibility issues with other gems.

**Comment by dazuma** [comment]
@jwg2s It shouldn't be locked to 0.9.x. It's dependency is `"faraday", "~> 0.9"`, which allows use of all later versions of faraday up to and including the latest 0.13.1. It just wouldn't pick up a faraday 1.0 (if that ever happens).

**Comment by TempestMia** [comment]
@dazuma `"faraday", "~> 0.9"` looks like it'll only allow use of later versions of 0.9, i.e. 0.9.1, 0.9.9 etc.

Also, looked this up cause we're in the same boat :)  Want to use this gem but it has a lot of version-locked dependencies which would cause us to not be able to update.

**Comment by dazuma** [comment]
@TempestMia Actually, `~> 0.9` does allow all later 0.x. The "twiddle-wakka" operator means, the furthest-right field must be greater than or equal to, but the second-furthest-right field must be exactly equal. So in this case, it means "0.x[.y]" where x >= 9, i.e. the major version must be "0" but the minor version can be >= 9 (and any patch version can be whatever). Two fields like this is commonly used for semantic versioning because it matches the compatibility semantics of major and minor versions.

What version dependency is failing for you?

**Comment by TempestMia** [comment]
@dazuma  I didn't realize it was depending on how far to the right you specify. TIL! Thanks!
